### ISSUE TITLE
Assertion Error caused by tqdm.auto

### ISSUE THREAD

**Issue by isunLt** [zhijian-liu/torchpack#32]
I get following Assertion Error while training with torchpack. Someone says it is because of `tqdm` in `tqdm.auto` and should change the line `from tqdm.auto import tqdm`in `progress.py` into `from tqdm import tqdm`. Is this right?
```python
Traceback (most recent call last):
  File "miniconda3/envs/torch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "miniconda3/envs/torch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers
    if w.is_alive():
  File "miniconda3/envs/torch/lib/python3.9/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
```

**Comment by zhijian-liu** [comment]
Could you try to install the nightly version (by `pip install git+https://github.com/zhijian-liu/torchpack.git`) to see if that works? Thanks!
