### ISSUE TITLE
KeyError: 'MASTER_HOST'

### ISSUE THREAD

**Issue by LeopoldACC** [zhijian-liu/torchpack#39]
hi , @zhijian-liu , when I want to use spvcnn in other task and try to run on multi-gpu with a Cloud Server Machine, KeyError: 'MASTER_HOST'
environment:
```
ubuntu 18.04
python 3.7.15
mpi4py 3.1.4
torchpack 0.3.1
```
the error is shown as below
```
--------------------------------------------------------------------------
WARNING: No preset parameters were found for the device that Open MPI
detected:

  Local host:            gz-tqr5m-35554-worker-0
  Device name:           mlx5_2
  Device vendor ID:      0x02c9
  Device vendor part ID: 4123

Default device parameters will be used, which may result in lower
performance.  You can edit any of the files specified by the
btl_openib_device_param_files MCA parameter to set values for your
device.

NOTE: You can turn off this warning by setting the MCA parameter
      btl_openib_warn_no_device_params_found to 0.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
WARNING: There was an error initializing an OpenFabrics device.

  Local host:   gz-tqr5m-35554-worker-0
  Local device: mlx5_2
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "monoscene/scripts/train_monoscene.py", line 54, in main
    dist.init()
  File "/data/packages/anaconda3/envs/monoscene/lib/python3.7/site-packages/torchpack/distributed/context.py", line 23, in init
    master_host = 'tcp://' + os.environ['MASTER_HOST']
  File "/data/packages/anaconda3/envs/monoscene/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'MASTER_HOST'
```

**Comment by LeopoldACC** [comment]
I solved the problem by git clone your codebase and `python setup.py develop`

**Comment by guangqianzhang** [comment]
i get the same problem，but  does not solved by `python setup.py develop` again ! wish i add a MASTER_HOST environment? do you kown the point and give me a hand?
